# Generated by Django 4.1.13 on 2024-11-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images/'),
        ),
    ]
